name: Plugin
version: '${project.version}'
main: com.spacerulerwill.plugin.Plugin
api-version: 1.19
commands:
  arena:
    description: Start the arena game mode
    usage: /<command> borderSize
libraries:
  - com.github.shynixn.structureblocklib:structureblocklib-bukkit-api:2.10.0
  - com.github.shynixn.structureblocklib:structureblocklib-bukkit-core:2.10.0